export const programmeList = [
  { value: "programmeA", label: "Programme A" },
  { value: "programmeB", label: "Programme B" },
  { value: "programmeC", label: "Programme C" },
  { value: "programmeD", label: "Programme D" },
  { value: "programmeE", label: "Programme E" },
  { value: "programmeF", label: "Programme F" },
];

export const locationsList = [
  { value: "locationA", label: "Location A" },
  { value: "locationB", label: "Location B" },
  { value: "locationC", label: "Location C" },
  { value: "locationD", label: "Location D" },
  { value: "locationE", label: "Location E" },
  { value: "locationF", label: "Location F" },
];

export const finalBeneficiariesList = [
  { value: "women", label: "women" },
  { value: "children", label: "children" },
  { value: "andfamilies", label: "families" },
  { value: "ethnicminorities", label: "ethnic minorities" },
  { value: "personswithdisabilities", label: "persons with disabilities" },
  { value: "youngpeople", label: "young people" },
  { value: "olderpeople", label: "older people" },
  { value: "marginalisedpeople", label: "marginalised people" },
  { value: "migrantsandrefugees", label: "migrants and refugees" },
  { value: "LGTBIQ+", label: "LGTBIQ+" },
  { value: "othercollective", label: "other collective" },
  { value: "adultpeople", label: "adult people" },
  { value: "localcommunities", label: "local communities" },
  { value: "Unemployed person", label: "Unemployed person" },
  { value: "Vulnerable person", label: "Vulnerable person" },
  { value: "Other", label: "Other" },
]

export const finalBeneficiariesList_es = [
  { value: "women", label: "mujeres" },
  { value: "children", label: "niños" },
  { value: "andfamilies", label: "familias" },
  { value: "ethnicminorities", label: "minorías étnicas" },
  { value: "personswithdisabilities", label: "personas con discapacidad" },
  { value: "youngpeople", label: "jóvenes" },
  { value: "olderpeople", label: "personas mayores" },
  { value: "marginalisedpeople", label: "personas marginadas" },
  { value: "migrantsandrefugees", label: "migrantes y refugiados" },
  { value: "LGTBIQ+", label: "LGTBIQ+" },
  { value: "othercollective", label: "otro colectivo" },
  { value: "adultpeople", label: "personas adultas" },
  { value: "localcommunities", label: "comunidades locales" },
  { value: "Unemployed person", label: "Persona desempleada" },
  { value: "Vulnerable person", label: "Persona vulnerable" },
  { value: "Other", label: "Otra" },
]

export const finalBeneficiariesList_fr = [
  { value: "women", label: "femmes" },
  { value: "children", label: "enfants" },
  { value: "andfamilies", label : "familles" },
  { value: "ethnicminorities", label : "minorités ethniques" },
  { value: "personswithdisabilities", label : "personnes handicapées" },
  { value: "youngpeople", label : "jeunes" },
  { value: "olderpeople", label : "personnes âgées" },
  { value: "marginalisedpeople", label : "personnes marginalisées" },
  { value: "migrantsandrefugees", label : "migrants et réfugiés" },
  { value: "LGTBIQ+", label: "LGTBIQ+" },
  { value: "othercollective", label : "autre collectif" },
  { value: "adultpeople", label : "personnes adultes" },
  { value: "localcommunities", label : "communautés locales" },
  { value: "Unemployed person", label: "Un chômeur" },
  { value: "Vulnerable person", label: "Personne vulnérable" },
  { value: "Other", label: "Autre" },
]

export const finalBeneficiariesList_hr = [
  { value: "women", label: "žene" },
  { value: "children", label: "djece" },
  { value: "andfamilies", label: "obitelji" },
  { value: "ethnicminorities", label: "ethnic minorities" },
  { value: "personswithdisabilities", label: "persons with disabilities" },
  { value: "youngpeople", label: "mladi ljudi" },
  { value: "olderpeople", label: "stariji ljudi" },
  { value: "marginalisedpeople", label: "marginalised people" },
  { value: "migrantsandrefugees", label: "migrants and refugees" },
  { value: "LGTBIQ+", label: "LGTBIQ+" },
  { value: "othercollective", label: "drugi kolektiv" },
  { value: "adultpeople", label: "odrasli ljudi" },
  { value: "localcommunities", label: "local community" },
  { value: "Unemployed person", label: "Nezaposlena osoba" },
  { value: "Vulnerable person", label: "Ranjiva osoba" },
  { value: "Other", label: "ostalo" },
]

export const finalBeneficiariesList_sq = [
  { value: "women", label: "gratë" },
  { value: "children", label: "fëmijë" },
  { value: "andfamilies", label: "familjet" },
  { value: "ethnicminorities", label: "minoritetet etnike" },
  { value: "personswithdisabilities", label: "personat me aftësi të kufizuara" },
  { value: "youngpeople", label: "të rinjtë" },
  { value: "olderpeople", label: "të moshuarit" },
  { value: "marginalisedpeople", label: "njerëz të margjinalizuar" },
  { value: "migrantsandrefugees", label: "migrantë dhe refugjatë" },
  { value: "LGTBIQ+", label: "LGTBIQ+" },
  { value: "Othercollective", label: "Kolektiv tjetër" },
  { value: "adultpeople", label: "njerëz të rritur" },
  { value: "localcommunities", label: "komunitetet lokale" },
  { value: "Unemployed person", label: "Person i papunë" },
  { value: "Vulnerable person", label: "Personi i cenueshëm" },
  { value: "Other", label: "Të tjera" },
]

export const volunteerBeneficiariesList = [
  { value: "women", label: "women" },
  { value: "ethnicminorities", label: "ethnic minority person" },
  { value: "personwithdisability", label: "person with disability" },
  { value: "youngperson", label: "young person" },
  { value: "olderperson", label: "older person" },
  { value: "vulnerableperson", label: "vulnerable person" },
  { value: "adultperson", label: "adult person" },
  { value: "unemployedperson", label: "unemployed person" },
]

export const volunteerBeneficiariesList_es = [
  { value: "women", label: "mujeres" },
  { value: "ethnicminorities", label: "persona de minoría étnica" },
  { value: "personwithdisability", label: "persona con discapacidad" },
  { value: "youngperson", label: "joven" },
  { value: "olderperson", label: "persona mayor" },
  { value: "vulnerableperson", label: "persona vulnerable" },
  { value: "adultperson", label: "persona adulta" },
  { value: "unemployedperson", label: "desempleado" },
]

export const volunteerBeneficiariesList_fr = [
  { value: "women", label: "femmes" },
  { value: "ethnicminorities", label : "personne appartenant à une minorité ethnique" },
  { value: "personwithdisability", label: "personne avec handicap" },
  { value: "youngperson", label : "jeune" },
  { value: "olderperson", label : "personne âgée" },
  { value: "vulnerableperson", label : "personne vulnérable" },
  { value: "adultperson", label : "personne adulte" },
  { value: "unemployedperson", label : "chômeur" },
]

export const volunteerBeneficiariesList_hr = [
  { value: "women", label: "žene" },
  { value: "ethnicminorities", label: "ethnic minorities person" },
  { value: "personwithdisability", label: "person with disability" },
  { value: "youngperson", label: "young person" },
  { value: "olderperson", label: "starija osoba" },
  { value: "vulnerableperson", label: "vulnerable person" },
  { value: "adultperson", label: "adult person" },
  { value: "unemployedperson", label: "unemployed person" },
]

export const volunteerBeneficiariesList_sq = [
  { value: "women", label: "gratë" },
  { value: "ethnicminorities", label: "person i pakicës etnike" },
  { value: "personwithdisability", label: "person me aftësi të kufizuar" },
  { value: "youngperson", label: "personi i ri" },
  { value: "olderperson", label: "person i moshuar" },
  { value: "vulnerableperson", label: "person i pambrojtur" },
  { value: "adultperson", label: "person i rritur" },
  { value: "unemployedperson", label: "person i papunë" },
]

export const typeofactivityList = [
  { value: "Raising or handling money/taking part in sponsored events", label: "Raising or handling money/taking part in sponsored events" },
  { value: "Leading a group/member of a committee", label: "Leading a group/member of a committee" },
  { value: "Getting other people involved", label: "Getting other people involved" },
  { value: "Organising or helping to run an activity or event", label: "Organising or helping to run an activity or event" },
  { value: "Visiting people", label: "Visiting people" },
  { value: "Befriending or mentoring people", label: "Befriending or mentoring people" },
  { value: "Giving advice/information/counselling", label: "Giving advice/information/counselling" },
  { value: "Secretarial", label: "Secretarial" },
  { value: "admin or clerical work", label: "admin or clerical work" },
  { value: "Providing transport/driving", label: "Providing transport/driving" },
  { value: "materialcreation", label: "material creation" },
  { value: "Representing", label: "Representing" },
  { value: "Campaigning", label: "Campaigning" },
  { value: "Other practical help", label: "Other practical help" },
  { value: "Other type of activity", label: "Other type of activity" },
]

export const typeofactivityList_es = [
  { value: "Raising or handling money/taking part in sponsored events", label: "Recaudar o manejar dinero/participar en eventos patrocinados" },
  { value: "Leading a group/member of a committee", label: "Liderando un grupo/miembro de un comité" },
  { value: "Getting other people involved", label: "Involucrar a otras personas" },
  { value: "Organising or helping to run an activity or event", label: "Organizar o ayudar a realizar una actividad o evento" },
  { value: "Visiting people", label: "Personas visitantes" },
  { value: "Befriending or mentoring people", label: "Hacerse amigo o ser mentor de personas" },
  { value: "Giving advice/information/counselling", label: "Dar consejo/información/asesoramiento" },
  { value: "Secretarial", label: "Secretaría" },
  { value: "admin or clerical work", label: "trabajo administrativo o administrativo" },
  { value: "Providing transport/driving", label: "Proporcionar transporte/conducir" },
  { value: "materialcreation", label: "creación de material" },
  { value: "Representing", label: "Representante" },
  { value: "Campaigning", label: "Campaña" },
  { value: "Other practical help", label: "Otra ayuda práctica" },
  { value: "Other type of activity", label: "Otro tipo de actividad" },
]

export const typeofactivityList_fr = [
  { value : "Raising or handling money/taking part in sponsored events", label : "Récolter ou gérer de l'argent/participer à des événements sponsorisés" },
  { value: "Leading a group/member of a committee", label: "Diriger un groupe/membre d'un comité" },
  { value: "Getting other people involved", label: "Implication d'autres personnes" },
  { value: "Organising or helping to run an activity or event", label: "Organiser ou aider à organiser une activité ou un événement" },
  { value : "Visiting people", label : "Visite de personnes" },
  { value: "Befriending or mentoring people", label: "Se lier d'amitié ou encadrer des personnes" },
  { value : "Giving advice/information/counselling", label : "Donner des conseils/informations/conseils" },
  { value: "Secretarial", label : "Secrétariat" },
  { value: "admin or clerical work", label : "travail administratif ou de bureau" },
  { value : "Providing transport/driving", label : "Fournir le transport/la conduite" },
  { value: "materialcreation", label : "création matérielle" },
  { value : "Representing", label : "Représentant" },
  { value: "Campaigning", label : "Campagne" },
  { value: "Other practical help", label: "Autre aide pratique" },
  { value : "Other type of activity", label : "Autre type d'activité" },
]

export const typeofactivityList_hr = [
  { value: "Raising or handling money/taking part in sponsored events", label: "Prikupljanje ili rukovanje novcem/sudjelovanje u sponzoriranim događajima" },
  { value: "Leading a group/member of a committee", label: "Vođenje grupe/član odbora" },
  { value: "Getting other people involved", label: "Uključivanje drugih ljudi" },
  { value: "Organising or helping to run an activity or event", label: "Organiziranje ili pomoć u izvođenju aktivnosti ili događaja" },
  { value: "Visiting people", label: "Posjećivanje ljudi" },
  { value: "Befriending or mentoring people", label: "Prijateljstvo ili mentorstvo ljudima" },
  { value: "Giving advice/information/counselling", label: "Davanje savjeta/informacija/savjetovanje" },
  { value: "Secretarial", label: "Tajnički" },
  { value: "admin or clerical work", label: "administratorski ili činovnički posao" },
  { value: "Providing transport/driving", label: "Pružanje prijevoza/vožnje" },
  { value: "materialcreation", label: "materialcreation"},
  { value: "Representing", label: "Representing" },
  { value: "Campaigning", label: "Campaigning" },
  { value: "Other practical help", label: "Ostala praktična pomoć" },
  { value: "Other type of activity", label: "Druga vrsta aktivnosti" },
]

export const typeofactivityList_sq = [
  {value: "Raising or handling money/taking part in sponsored events", label: "Ngritja ose trajtimi i parave/marrja pjesë në ngjarje të sponsorizuara" },
  { value: "Leading a group/member of a committee", label: "Udhëheqja e një grupi/anëtari i një komiteti" },
  { value: "Getting other people involved", label: "Përfshirja e njerëzve të tjerë" },
  { value: "Organising or helping to run an activity or event", label: "Organising or help to running a activity or event" },
  { value: "Visiting people", label: "Visiting people" },
  { value: "Befriending or mentoring people", label: "Të bësh miqësi ose të mentorosh njerëz" },
  { value: "Giving advice/information/counselling", label: "Dhënia e këshillave/informacioneve/këshillimit" },
  { value: "Secretarial", label: "Sekretari" },
  { value: "admin or clerical work", label: "punë administratore ose klerikale" },
  { value: "Providing transport/driving", label: "Providing transport/driving" },
  { value: "materialcreation", label: "krijim material" },
  { value: "Representing", label: "Përfaqëson" },
  { value: "Campaigning", label: "Campaigning" },
  { value: "Other practical help", label: "Ndihmë tjetër praktike" },
  { value: "Other type of activity", label: "Lloji tjetër i aktivitetit" },
]

export const SDGList = [
  { value: "SDG1", label: "SDG1 - No poverty" },
  { value: "SDG2", label: "SDG2 - Zero hunger" },
  { value: "SDG3", label: "SDG3 - Good health and well-being" },
  { value: "SDG4", label: "SDG4 - Quality education" },
  { value: "SDG5", label: "SDG5 - Gender equality" },
  { value: "SDG6", label: "SDG6 - Clean water and sanitation" },
  { value: "SDG7", label: "SDG7 - Affordable and clean energy" },
  { value: "SDG8", label: "SDG8 - Decent work and economic growth" },
  { value: "SDG9", label: "SDG9 - Industry, innovation and infrastructure" },
  { value: "SDG10", label: "SDG10 - Reduced inequalities" },
  { value: "SDG11", label: "SDG11 - Sustainable cities and communities" },
  { value: "SDG12", label: "SDG12 - Responsible consumption and production" },
  { value: "SDG13", label: "SDG13 - Climate action" },
  { value: "SDG14", label: "SDG14 - Life below water" },
  { value: "SDG15", label: "SDG15 - Life on land" },
  { value: "SDG16", label: "SDG16 - Peace, justice, and strong institutions" },
  { value: "SDG17", label: "SDG17 - Partnerships for the goals" },
]

export const SDGList_es = [
  { value: "SDG1", label: "SDG1 - Fin de la pobreza" },
  { value: "SDG2", label: "SDG2 - Hambre cero" },
  { value: "SDG3", label: "SDG3 - Buena salud y bienestar" },
  { value: "SDG4", label: "SDG4 - Educación de calidad" },
  { value: "SDG5", label: "SDG5 - Igualdad de género" },
  { value: "SDG6", label: "SDG6 - Agua limpia y saneamiento" },
  { value: "SDG7", label: "SDG7 - Energía limpia y asequible" },
  { value: "SDG8", label: "SDG8 - Trabajo decente y crecimiento económico" },
  { value: "SDG9", label: "SDG9 - Industria, innovación e infraestructura" },
  { value: "SDG10", label: "SDG10 - Reducción de las desigualdades" },
  { value: "SDG11", label: "SDG11 - Ciudades y comunidades sostenibles" },
  { value: "SDG12", label: "SDG12 - Producción y consumo responsables" },
  { value: "SDG13", label: "SDG13 - Acción por el clima" },
  { value: "SDG14", label: "SDG14 - Vida submarina" },
  { value: "SDG15", label: "SDG15 - Vida terrestre" },
  { value: "SDG16", label: "SDG16 - Paz, justicia e instituciones sólidas" },
  { value: "SDG17", label: "SDG17 - Alianzas para lograr los objetivos" },
]

export const SDGList_fr = [
  { value: "SDG1", label : "SDG1 - Pas de pauvreté" },
  { value: "SDG2", label: "SDG2 - Faim zéro" },
  { value: "SDG3", label : "SDG3 - Bonne santé et bien-être" },
  { value: "SDG4", label : "SDG4 - Éducation de qualité" },
  { value: "SDG5", label : "SDG5 - Égalité des genres" },
  { value: "SDG6", label : "SDG6 - Eau potable et assainissement" },
  { value: "SDG7", label : "SDG7 - Énergie propre et abordable" },
  { value: "SDG8", label : "SDG8 - Travail décent et croissance économique" },
  { value: "SDG9", label : "SDG9 - Industrie, innovation et infrastructures" },
  { value: "SDG10", label : "SDG10 - Inégalités réduites" },
  { value: "SDG11", label : "SDG11 - Villes et communautés durables" },
  { value: "SDG12", label : "SDG12 - Consommation et production responsables" },
  { value: "SDG13", label: "SDG13 - Action climatique" },
  { value: "SDG14", label: "SDG14 - La vie sous l'eau" },
  { value: "SDG15", label : "SDG15 - Vie terrestre" },
  { value: "SDG16", label : "SDG16 - Paix, justice et institutions fortes" },
  { value : "SDG17", label : "SDG17 - Partenariats pour les objectifs" },
]

export const SDGList_hr = [
  { value: "SDG1", label: "SDG1 - Nema siromaštva" },
  { value: "SDG2", label: "SDG2 - Zero hunger" },
  { value: "SDG3", label: "SDG3 - Dobro zdravlje i blagostanje" },
  { value: "SDG4", label: "SDG4 - Kvalitetno obrazovanje" },
  { value: "SDG5", label: "SDG5 - Rodna ravnopravnost" },
  { value: "SDG6", label: "SDG6 - Čista voda i sanitacija" },
  { value: "SDG7", label: "SDG7 - Pristupačna i čista energija" },
  { value: "SDG8", label: "SDG8 - Dostojanstven rad i ekonomski rast" },
  { value: "SDG9", label: "SDG9 - Industrija, inovacija i infrastruktura" },
  { value: "SDG10", label: "SDG10 - Smanjene nejednakosti" },
  { value: "SDG11", label: "SDG11 - Održivi gradovi i zajednice" },
  { value: "SDG12", label: "SDG12 - Odgovorna potrošnja i proizvodnja" },
  { value: "SDG13", label: "SDG13 - Climate action" },
  { value: "SDG14", label: "SDG14 - Život ispod vode" },
  { value: "SDG15", label: "SDG15 - Život na kopnu" },
  { value: "SDG16", label: "SDG16 - Mir, pravda i jake institucije" },
  { value: "SDG17", label: "SDG17 - Partnerstva za ciljeve" },
]

export const SDGList_sq = [
  { value: "SDG1", label: "SDG1 - Pa varfëri" },
  { value: "SDG2", label: "SDG2 - Zero uria" },
  { value: "SDG3", label: "SDG3 - Shëndet dhe mirëqenie e mirë" },
  { value: "SDG4", label: "SDG4 - Edukim cilësor" },
  { value: "SDG5", label: "SDG5 - Barazi gjinore" },
  { value: "SDG6", label: "SDG6 - Ujë i pastër dhe kanalizime" },
  { value: "SDG7", label: "SDG7 - Energji e përballueshme dhe e pastër" },
  { value: "SDG8", label: "SDG8 - Punë e denjë dhe rritje ekonomike" },
  { value: "SDG9", label: "SDG9 - Industri, inovacion dhe infrastrukturë" },
  { value: "SDG10", label: "SDG10 - Pabarazitë e reduktuara" },
  { value: "SDG11", label: "SDG11 - Qytete dhe komunitete të qëndrueshme" },
  { value: "SDG12", label: "SDG12 - Konsumi dhe prodhimi i përgjegjshëm" },
  { value: "SDG13", label: "SDG13 - Veprimi i klimës" },
  { value: "SDG14", label: "SDG14 - Jeta nën ujë" },
  { value: "SDG15", label: "SDG15 - Jeta në tokë" },
  { value: "SDG16", label: "SDG16 - Paqe, drejtësi dhe institucione të forta" },
  { value: "SDG17", label: "SDG17 - Partneritete për qëllimet" },
]
 
export const skillsList = [
  { value: "social skills", label: "social skills" },
  { value: "organisational skills", label: "organisational skills" },
  { value: "attitudinal skills", label: "attitudinal skills" },
  { value: "creative skills", label: "creative skills" },
  { value: "mathematical and scientific skills", label: "mathematical and scientific skills" },
  { value: "digital skills", label: "digital skills" },
  { value: "communication skills", label: "communication skills" },
  { value: "environmental protection skills", label: "environmental protection skills" },
  { value: "other", label: "other" },
];

export const skillsList_es = [
  { value: "social skills", label: "habilidades sociales" },
  { value: "organisational skills", label: "habilidades organizativas" },
  { value: "attitudinal skills", label: "habilidades de actitud" },
  { value: "creative skills", label: "habilidades creativas" },
  { value: "mathematical and scientific skills", label: "habilidades matemáticas y científicas" },
  { value: "digital skills", label: "habilidades digitales" },
  { value: "communication skills", label: "habilidades de comunicación" },
  { value: "environmental protection skills", label: "habilidades de protección ambiental" },
  { value: "other", label: "otro" },
];

export const skillsList_fr = [
  { value: "social skills", label : "compétences sociales" },
  { value: "organisational skills", label : "compétences organisationnelles" },
  { value: "attitudinal skills", label: "compétences comportementales" },
  { value: "creative skills", label : "compétences créatives" },
  { value : "mathematical and scientific skills", label : "compétences mathématiques et scientifiques" },
  { value: "digital skills", label : "compétences numériques" },
  { value: "communication skills", label : "compétences en communication" },
  { value: "environmental protection skills", label : "compétences en matière de protection de l'environnement" },
  { value: "other", label: "autre" },
];

export const skillsList_hr = [
  { value: "social skills", label: "socijalne vještine" },
  { value: "organisational skills", label: "organizacijske vještine" },
  { value: "attitudinal skills", label: "vještine stava" },
  { value: "creative skills", label: "kreativne vještine" },
  { value: "mathematical and scientific skills", label: "matematičke i znanstvene vještine" },
  { value: "digital skills", label: "digitalne vještine" },
  { value: "communication skills", label: "komunikacijske vještine" },
  { value: "environmental protection skills", label: "vještine zaštite okoliša" },
  { value: "other", label: "drugo" },
];

export const skillsList_sq = [
  { value: "social skills", label: "social skills" },
  { value: "organisational skills", label: "organizational skills" },
  { value: "attitudinal skills", label: "attitudinal skills" },
  { value: "creative skills", label: "aftësi krijuese" },
  { value: "mathematical and scientific skills", label: "aftësi matematikore dhe shkencore" },
  { value: "digital skills", label: "aftësi dixhitale" },
  { value: "communication skills", label: "aftësi komunikimi" },
  { value: "environmental protection skills", label: "aftësi për mbrojtjen e mjedisit" },
  { value: "other", label: "tjera" },
];

export const sessionnameList = [
  { value: "Raising or handling money/taking part in sponsored events", label: "Raising or handling money/taking part in sponsored events" },
  { value: "Leading a group/member of a committee", label: "Leading a group/member of a committee" },
  { value: "Getting other people involved", label: "Getting other people involved" },
  { value: "Organising or helping to run an activity or event", label: "Organising or helping to run an activity or event" },
  { value: "Visiting people", label: "Visiting people" },
  { value: "Befriending or mentoring people", label: "Befriending or mentoring people" },
  { value: "Giving advice/information/counselling", label: "Giving advice/information/counselling" },
  { value: "Secretarial", label: "Secretarial" },
  { value: "admin or clerical work", label: "admin or clerical work" },
  { value: "Providing transport/driving", label: "Providing transport/driving" },
  { value: "Representing", label: "Representing" },
  { value: "Campaigning", label: "Campaigning" },
  { value: "Other practical help (e.g. helping out at school, shopping)", label: "Other practical help (e.g. helping out at school, shopping)" },
]

export const sessionnameList_es = [
  { value: "Raising or handling money/taking part in sponsored events", label: "Recaudar o manejar dinero/participar en eventos patrocinados" },
  { value: "Leading a group/member of a committee", label: "Liderando un grupo/miembro de un comité" },
  { value: "Getting other people involved", label: "Involucrar a otras personas" },
  { value: "Organising or helping to run an activity or event", label: "Organizar o ayudar a realizar una actividad o evento" },
  { value: "Visiting people", label: "Personas visitantes" },
  { value: "Befriending or mentoring people", label: "Hacerse amigo o ser mentor de personas" },
  { value: "Giving advice/information/counselling", label: "Dar consejo/información/asesoramiento" },
  { value: "Secretarial", label: "Secretaría" },
  { value: "admin or clerical work", label: "Trabajo administrativo o administrativo" },
  { value: "Providing transport/driving", label: "Proporcionar transporte/conducir" },
  { value: "Representing", label: "Representante" },
  { value: "Campaigning", label: "Campaña" },
  { value: "Other practical help (e.g. helping out at school, shopping)", label: "Otra ayuda práctica (por ejemplo, ayudar en la escuela, ir de compras)" },
]

export const sessionnameList_fr = [
  { value: "Raising or handling money/taking part in sponsored events", label: "Récolter ou gérer de l'argent/participer à des événements sponsorisés" },
  { value: "Leading a group/member of a committee", label: "Diriger un groupe/membre d'un comité" },
  { value: "Getting other people involved", label: "Implication d'autres personnes" },
  { value: "Organising or helping to run an activity or event", label: "Organiser ou aider à organiser une activité ou un événement" },
  { value: "Visiting people", label: "Visite de personnes" },
  { value: "Befriending or mentoring people", label: "Se lier d'amitié ou encadrer des personnes" },
  { value: "Giving advice/information/counselling", label: "Donner des conseils/informations/conseils" },
  { value: "Secretarial", label: "Secrétariat" },
  { value: "admin or clerical work", label: "travail administratif ou de bureau" },
  { value: "Providing transport/driving", label: "Fournir le transport/la conduite" },
  { value: "Representing", label: "Représentant" },
  { value: "Campaigning", label: "Campagne" },
  { value: "Other practical help (e.g. helping out at school, shopping)", label: "Autre aide pratique (par exemple, aider à l'école, faire les courses)" },
]

export const sessionnameList_hr = [
  { value: "Raising or handling money/taking part in sponsored events", label: "Prikupljanje ili rukovanje novcem/sudjelovanje u sponzoriranim događajima" },
  { value: "Leading a group/member of a committee", label: "Vođenje grupe/član odbora" },
  { value: "Getting other people involved", label: "Uključivanje drugih ljudi" },
  { value: "Organising or helping to run an activity or event", label: "Organiziranje ili pomoć u izvođenju aktivnosti ili događaja" },
  { value: "Visiting people", label: "Posjećivanje ljudi" },
  { value: "Befriending or mentoring people", label: "Prijateljstvo ili mentorstvo ljudima" },
  { value: "Giving advice/information/counselling", label: "Davanje savjeta/informacija/savjetovanje" },
  { value: "Secretarial", label: "Tajnički" },
  { value: "admin or clerical work", label: "administratorski ili činovnički posao" },
  { value: "Providing transport/driving", label: "Pružanje prijevoza/vožnje" },
  { value: "Representing", label: "Representing" },
  { value: "Campaigning", label: "Campaigning" },
  { value: "Other practical help (e.g. helping out at school, shopping)", label: "Druga praktična pomoć (npr. pomoć u školi, kupovina)" },
]

export const sessionnameList_sq = [
  { value: "Raising or handling money/taking part in sponsored events", label: "Ngritja ose trajtimi i parave/marrja pjesë në ngjarje të sponsorizuara" },
  { value: "Leading a group/member of a committee", label: "Drejtimi i një grupi/anëtari i një komiteti" },
  { value: "Getting other people involved", label: "Përfshirja e njerëzve të tjerë" },
  { value: "Organising or helping to run an activity or event", label: "Organising or help to running a activity or event" },
  { value: "Visiting people", label: "Visiting people" },
  { value: "Befriending or mentoring people", label: "Të bësh miqësi ose të mentorosh njerëz" },
  { value: "Giving advice/information/counselling", label: "Dhënia e këshillave/informacioneve/këshillimit" },
  { value: "Secretarial", label: "Sekretari" },
  { value: "admin or clerical work", label: "punë administratore ose klerikale" },
  { value: "Providing transport/driving", label: "Providing transport/driving" },
  { value: "Representing", label: "Përfaqëson" },
  { value: "Campaigning", label: "Campaigning" },
  { value: "Other practical help (e.g. helping out at school, shopping)", label: "Ndihmë tjetër praktike (p.sh. ndihma në shkollë, pazar)" },
]

