export const reasonsList = [
  { value: "Not enough time - due to changing home/work circumstances", label: "Not enough time - due to changing home/work circumstances" },
  { value: "Not enough time – getting involved took up too much time", label: "Not enough time – getting involved took up too much time" },
  { value: "Group/club/organisation finished/closed", label: "Group/club/organisation finished/closed" },
  { value: "Moved away from area", label: "Moved away from area" },
  { value: "Due to health problems or old age", label: "Due to health problems or old age" },
  { value: "Group/club/organisation wasn't relevant to me anymore", label: "Group/club/organisation wasn't relevant to me anymore" },
  { value: "Lost interest", label: "Lost interest" },
  { value: "It was a one-off activity or event", label: "It was a one-off activity or event" },
  { value: "Felt I had done my bit/ someone else’s turn to get involved", label: "Felt I had done my bit/ someone else’s turn to get involved" },
  { value: "Got involved in another activity instead", label: "Got involved in another activity instead" },
  { value: "Didn't get asked to do the things I'd like to; Felt the group/club/organisation was badly organised", label: "Didn't get asked to do the things I'd like to; Felt the group/club/organisation was badly organised" },
  { value: "Felt my efforts weren't always appreciated; It was too bureaucratic/ too much concern about risk and liability", label: "CamFelt my efforts weren't always appreciated; It was too bureaucratic/ too much concern about risk and liabilitypaigning" },
  { value: "Activity linked to my school/college/university/job I have now left", label: "Activity linked to my school/college/university/job I have now left" },
  { value: "I didn't feel my contribution made a difference/ I didn’t understand my impact", label: "I didn't feel my contribution made a difference/ I didn’t understand my impact" },
]

export const reasonsList_es = [
  { value: "Not enough time - due to changing home/work circumstances", label: "No hay suficiente tiempo - debido a cambios en las circunstancias del hogar/trabajo" },
  { value: "Not enough time – getting involved took up too much time", label: "No hay suficiente tiempo - involucrarse tomó demasiado tiempo" },
  { value: "Group/club/organisation finished/closed", label: "Grupo/club/organización terminado/cerrado" },
  { value: "Moved away from area", label: "Alejado del área" },
  { value: "Due to health problems or old age", label: "Por problemas de salud o vejez" },
  { value: "Group/club/organisation wasn't relevant to me anymore", label: "El grupo/club/organización ya no era relevante para mí" },
  { value: "Lost interest", label: "Pérdida de interés" },
  { value: "It was a one-off activity or event", label: "Fue una actividad o evento puntual" },
  { value: "Felt I had done my bit/ someone else’s turn to get involved", label: "Sentí que había aportado mi granito de arena/ el turno de alguien más de involucrarse" },
  { value: "Got involved in another activity instead", label: "En su lugar, me involucré en otra actividad" },
  { value: "Didn't get asked to do the things I'd like to; Felt the group/club/organisation was badly organised", label: "No me pidieron que hiciera las cosas que me gustaría hacer; Sentí el grupo/club/organización estaba mal organizado" },
  { value: "Felt my efforts weren't always appreciated; It was too bureaucratic/ too much concern about risk and liability", label: "CamFelt mis esfuerzos no siempre fueron apreciados; era demasiado burocrático/demasiada preocupación por el riesgo y responsabilidad" },
  { value: "Activity linked to my school/college/university/job I have now left", label: "Actividad vinculada a mi escuela/colegio/universidad/trabajo que dejé" },
  { value: "I didn't feel my contribution made a difference/ I didn’t understand my impact", label: "No sentí que mi contribución marcó una diferencia/ No entendí mi impacto" },
]

export const reasonsList_fr = [
  { value: "Not enough time - due to changing home/work circumstances", label: "Pas assez de temps - en raison de changements dans les circonstances à la maison/au travail" },
  { value: "Not enough time – getting involved took up too much time", label: "Pas assez de temps – s'impliquer a pris trop de temps" },
  { value: "Group/club/organisation finished/closed", label: "Groupe/club/organisation terminé/fermé" },
  { value : "Moved away from area", label : "Éloigné de la zone" },
  { value : "Due to health problems or old age", label : "En raison de problèmes de santé ou de la vieillesse" },
  { value: "Group/club/organisation wasn't relevant to me anymore", label: "Le groupe/club/organisation ne me concernait plus" },
  { value : "Lost interest", label : "Intérêt perdu" },
  { value: "It was a one-off activity or event", label: "C'était une activité ou un événement ponctuel" },
  { value: "Felt I had done my bit/ someone else’s turn to get involved", label: "Je sentais que j'avais fait ma part/au tour de quelqu'un d'autre de s'impliquer" },
  { value: "Got involved in another activity instead", label: "Je me suis impliqué dans une autre activité à la place" },
  { value : "Didn't get asked to do the things I'd like to; Felt the group/club/organisation was badly organised", label : "On ne m'a pas demandé de faire les choses que j'aimerais faire ; j'ai senti le groupe/club/organisation était mal organisé" },
  { value : "Felt my efforts weren't always appreciated; It was too bureaucratic/ too much concern about risk and liability", label : "CamFelt, mes efforts n'étaient pas toujours appréciés ; c'était trop bureaucratique/trop d'inquiétude concernant le risque et responsabilité" },
  { value: "Activity linked to my school/college/university/job I have now left", label: "Activité liée à mon école/collège/université/emploi que j'ai maintenant quitté" },
  { value: "I didn't feel my contribution made a difference/ I didn’t understand my impact", label: "Je n'ai pas senti que ma contribution avait fait une différence/Je n'ai pas compris mon impact" },
]

export const reasonsList_hr = [
  { value: "Not enough time - due to changing home/work circumstances", label: "Nema dovoljno vremena - zbog promjene okolnosti doma/posla" },
  { value: "Not enough time – getting involved took up too much time", label: "Nema dovoljno vremena – uključivanje je oduzelo previše vremena" },
  { value: "Group/club/organisation finished/closed", label: "Grupa/klub/organizacija završena/zatvorena" },
  { value: "Moved away from area", label: "Odmaknuto od područja" },
  { value: "Due to health problems or old age", label: "Zbog zdravstvenih problema ili starosti" },
  { value: "Group/club/organisation wasn't relevant to me anymore", label: "Grupa/klub/organizacija mi više nije bila relevantna" },
  { value: "Lost interest", label: "Izgubljeno zanimanje" },
  { value: "It was a one-off activity or event", label: "Bila je to jednokratna aktivnost ili događaj" },
  { value: "Felt I had done my bit/ someone else’s turn to get involved", label: "Osjetio sam da sam učinio svoj dio/netko drugi je bio na redu da se uključi" },
  { value: "Got involved in another activity instead", label: "Umjesto toga se uključio u drugu aktivnost" },
  { value: "Didn't get asked to do the things I'd like to; Felt the group/club/organisation was badly organised", label: "Nisam tražio da radim stvari koje bih želio; Čini mi se grupa/klub/organizacija je bila loše organizirana" },
  { value: "Felt my efforts weren't always appreciated; It was too bureaucratic/ too much concern about risk and liability", label: "CamFelt moj trud nije uvijek cijenjen; Bilo je previše birokratski/previše zabrinutosti oko rizika i paigning odgovornosti" },
  { value: "Activity linked to my school/college/university/job I have now left", label: "Aktivnost povezana s mojom školom/fakultetom/sveučilištem/poslom koji sam sada napustio" },
  { value: "I didn't feel my contribution made a difference/ I didn’t understand my impact", label: "Nisam osjećao da je moj doprinos napravio razliku/ Nisam razumio svoj utjecaj" },
]

export const reasonsList_sq = [
  { value: "Not enough time - due to changing home/work circumstances", label: "Nuk është e mjaftueshme kohë - për shkak të ndryshimit të rrethanave të shtëpisë/punës" },
  { value: "Not enough time – getting involved took up too much time", label: "Nuk mjafton kohë - përfshirja ka marrë shumë kohë" },
  { value: "Group/club/organisation finished/closed", label: "Grupi/klubi/organizata e përfunduar/mbyllur" },
  { value: "Moved away from area", label: "Larguar nga zona" },
  { value: "Due to health problems or old age", label: "Për shkak të problemeve shëndetësore ose pleqërisë" },
  { value: "Group/club/organisation wasn't relevant to me anymore", label: "Grupi/klubi/organizata nuk ishte më relevante për mua" },
  { value: "Lost interest", label: "Interesi i humbur" },
  { value: "It was a one-off activity or event", label: "Ishte një aktivitet ose ngjarje një herë" },
  { value: "Felt I had done my bit/ someone else’s turn to get involved", label: "Ndjeva se kisha bërë bit timin/ dikujt tjetër radha për t'u përfshirë" },
  { value: "Got involved in another activity instead", label: "Në vend të tij u përfshiva në një aktivitet tjetër" },
  { value: "Didn't get asked to do the things I'd like to; Felt the group/club/organisation was badly organised", label: "Nuk më kërkuan të bëja gjërat që do të doja; Ndjeva grupi/klubi/organizata ishte e organizuar keq" },
  { value: "Felt my efforts weren't always appreciated; It was too bureaucratic/ too much concern about risk and liability", label: "CamFelt që përpjekjet e mia nuk u vlerësuan gjithmonë; Ishte shumë burokratike/ shumë shqetësim për rrezikun dhe pagimi i përgjegjësisë" },
  { value: "Activity linked to my school/college/university/job I have now left", label: "Aktiviteti i lidhur me shkollën/kolegjin/universitetin/punën time që kam lënë tani" },
  { value: "I didn't feel my contribution made a difference/ I didn’t understand my impact", label: "Nuk ndjeva se kontributi im bëri ndryshim/ Nuk e kuptova ndikimin tim" },
]
