export const organisationObjetivesList = [
  { value: "01", label: "Community activity/mutual support" },
  { value: "02", label: "Emergency response" },
  { value: "03", label: "Community peacekeeping" },
  { value: "04", label: "Social assistance" },
  { value: "05", label: "Personal assistance" },
  { value: "06", label: "Children and youth" },
  { value: "07", label: "Human rights, advocacy, and politics" },
  { value: "08", label: "Economic justice" },
  { value: "09", label: "Faith-based" },
  { value: "10", label: "Religious volunteering" },
  { value: "11", label: "Education" },
  { value: "12", label: "Health care" },
  { value: "13", label: "Environment" },
  { value: "14", label: "Data collection" },
  { value: "15", label: "Promotion of knowledge" },
  { value: "16", label: "Promotion of commerce" },
  { value: "17", label: "Law and legal services" },
  { value: "18", label: "Culture" },
  { value: "19", label: "Recreation" },
  { value: "20", label: "Other" },
];

export const organisationObjetivesList_es = [
  { value: "01", label: "Actividad comunitaria/apoyo mutuo" },
  { value: "02", label: "Respuesta de emergencia" },
  { value: "03", label: "Mantenimiento de la paz comunitario" },
  { value: "04", label: "Asistencia social" },
  { value: "05", label: "Asistencia personal" },
  { value: "06", label: "Niños y jóvenes" },
  { value: "07", label: "Derechos humanos, promoción y política" },
  { value: "08", label: "Justicia económica" },
  { value: "09", label: "Basado en la fe" },
  { value: "10", label: "Voluntariado religioso" },
  { value: "11", label: "Educación" },
  { value: "12", label: "Cuidado de la salud" },
  { value: "13", label: "Medio ambiente" },
  { value: "14", label: "Recopilación de datos" },
  { value: "15", label: "Promoción del conocimiento" },
  { value: "16", label: "Promoción del comercio" },
  { value: "17", label: "Derecho y servicios legales" },
  { value: "18", label: "Cultura" },
  { value: "19", label: "Recreación" },
  { value: "20", label: "Otro" },
];

export const organisationObjetivesList_fr = [
  { value: "01", label : "Activité communautaire/soutien mutuel" },
  { value: "02", label : "Intervention d'urgence" },
  { value: "03", label : "Maintien de la paix communautaire" },
  { value : "04", label : "Assistance sociale" },
  { value : "05", label : "Assistance personnelle" },
  { value: "06", label : "Enfants et jeunes" },
  { value : "07", label : "Droits de l'homme, plaidoyer et politique" },
  { value: "08", label : "Justice économique" },
  { value: "09", label : "Basé sur la foi" },
  { value: "10", label : "Volontariat religieux" },
  { value: "11", label: "Éducation" },
  { value: "12", label: "Soins de santé" },
  { value: "13", label: "Environnement" },
  { value: "14", label : "Collecte de données" },
  { value : "15", label : "Promotion des connaissances" },
  { value : "16", label : "Promotion du commerce" },
  { value: "17", label : "Droit et services juridiques" },
  { value: "18", label: "Culture" },
  { value: "19", label : "Loisirs" },
  { value: "20", label: "Autre" },
];

export const organisationObjetivesList_hr = [
  { value: "01", label: "Aktivnost zajednice/međusobna podrška" },
  { value: "02", label: "Hitni odgovor" },
  { value: "03", label: "Održavanje mira u zajednici" },
  { value: "04", label: "Socijalna pomoć" },
  { value: "05", label: "Osobna pomoć" },
  { value: "06", label: "Djeca i mladi" },
  { value: "07", label: "Ljudska prava, zagovaranje i politika" },
  { value: "08", label: "Ekonomska pravda" },
  { value: "09", label: "Na temelju vjere" },
  { value: "10", label: "Vjersko volontiranje" },
  { value: "11", label: "Education" },
  { value: "12", label: "Zdravstvena njega" },
  { value: "13", label: "Okruženje" },
  { value: "14", label: "Prikupljanje podataka" },
  { value: "15", label: "Promicanje znanja" },
  { value: "16", label: "Promicanje trgovine" },
  { value: "17", label: "Pravo i pravne usluge" },
  { value: "18", label: "Culture" },
  { value: "19", label: "Recreation" },
  { value: "20", label: "Ostalo" },
];

export const organisationObjetivesList_sq = [
  { value: "01", label: "Aktiviteti i komunitetit/mbështetje reciproke" },
  { value: "02", label: "Përgjigjja e urgjencës" },
  { value: "03", label: "Paqeruajtja e komunitetit" },
  { value: "04", label: "Asistencë sociale" },
  { value: "05", label: "Asistencë personale" },
  { value: "06", label: "Fëmijët dhe të rinjtë" },
  { value: "07", label: "Të drejtat e njeriut, avokatia dhe politika" },
  { value: "08", label: "Drejtësia ekonomike" },
  { value: "09", label: "Bazuar në besim" },
  { value: "10", label: "Vullnetarizmi fetar" },
  { value: "11", label: "Edukimi" },
  { value: "12", label: "Kujdes shëndetësor" },
  { value: "13", label: "Mjedis" },
  { value: "14", label: "Mbledhja e të dhënave" },
  { value: "15", label: "Promovimi i njohurive" },
  { value: "16", label: "Promovimi i tregtisë" },
  { value: "17", label: "Ligji dhe shërbimet ligjore" },
  { value: "18", label: "Kultura" },
  { value: "19", label: "Rekreacion" },
  { value: "20", label: "Tjetër" },
];
