export const levelOperationList = [
  { value: "01", label: "local" },
  { value: "02", label: "regional" },
  { value: "03", label: "national" },
  { value: "04", label: "international" },
]

export const levelOperationList_es = [
  { value: "01", label: "local" },
  { value: "02", label: "regional" },
  { value: "03", label: "nacional" },
  { value: "04", label: "internacional" },
]

export const levelOperationList_fr = [
  { value: "01", label: "local" },
  { value: "02", label: "régional" },
  { value: "03", label: "national" },
  { value: "04", label: "international" },
]

export const levelOperationList_hr = [
  { value: "01", label: "lokalno" },
  { value: "02", label: "regionalno" },
  { value: "03", label: "nacionalni" },
  { value: "04", label: "international" },
]

export const levelOperationList_sq = [
  { value: "01", label: "lokale" },
  { value: "02", label: "rajonale" },
  { value: "03", label: "kombëtare" },
  { value: "04", label: "ndërkombëtare" },
]

export const programmeTypeList = [
  { value: "01", label: "Community activity/mutual support" },
  { value: "02", label: "Emergency response" },
  { value: "03", label: "Community peacekeeping" },
  { value: "04", label: "Social assistance" },
  { value: "05", label: "Personal assistance" },
  { value: "06", label: "Children and youth" },
  { value: "07", label: "Human rights, advocacy, and politics" },
  { value: "08", label: "Economic justice" },
  { value: "09", label: "Faith-based" },
  { value: "10", label: "religious volunteering" },
  { value: "11", label: "Education" },
  { value: "12", label: "Health care" },
  { value: "13", label: "Environment" },
  { value: "14", label: "Data collection" },
  { value: "15", label: "Promotion of knowledge" },
  { value: "16", label: "Promotion of commerce" },
  { value: "17", label: "Law and legal services" },
  { value: "18", label: "Culture" },
  { value: "19", label: "Recreation" },
  { value: "20", label: "Other" },
]

export const programmeTypeList_es = [
  { value: "01", label: "Actividad comunitaria/apoyo mutuo" },
   { value: "02", label: "Respuesta de emergencia" },
   { value: "03", label: "Mantenimiento de la paz comunitario" },
   { value: "04", label: "Asistencia social" },
   { value: "05", label: "Asistencia personal" },
   { value: "06", label: "Niños y jóvenes" },
   { value: "07", label: "Derechos humanos, promoción y política" },
   { value: "08", label: "Justicia económica" },
   { value: "09", label: "Basado en la fe" },
   { value: "10", label: "voluntariado religioso" },
   { value: "11", label: "Educación" },
   { value: "12", label: "Cuidado de la salud" },
   { value: "13", label: "Medio ambiente" },
   { value: "14", label: "Recopilación de datos" },
   { value: "15", label: "Promoción del conocimiento" },
   { value: "16", label: "Promoción del comercio" },
   { value: "17", label: "Derecho y servicios legales" },
   { value: "18", label: "Cultura" },
   { value: "19", label: "Recreación" },
   { value: "20", label: "Otro" },
]

export const programmeTypeList_fr = [
  { value: "01", label : "Activité communautaire/soutien mutuel" },
  { value: "02", label : "Intervention d'urgence" },
  { value: "03", label : "Maintien de la paix communautaire" },
  { value : "04", label : "Assistance sociale" },
  { value : "05", label : "Assistance personnelle" },
  { value: "06", label : "Enfants et jeunes" },
  { value : "07", label : "Droits de l'homme, plaidoyer et politique" },
  { value: "08", label : "Justice économique" },
  { value: "09", label : "Basé sur la foi" },
  { value: "10", label : "volontariat religieux" },
  { value: "11", label: "Éducation" },
  { value: "12", label: "Soins de santé" },
  { value: "13", label: "Environnement" },
  { value: "14", label : "Collecte de données" },
  { value : "15", label : "Promotion des connaissances" },
  { value : "16", label : "Promotion du commerce" },
  { value: "17", label : "Droit et services juridiques" },
  { value: "18", label: "Culture" },
  { value: "19", label : "Loisirs" },
  { value: "20", label: "Autre" },
]

export const programmeTypeList_hr = [
  { value: "01", label: "Aktivnost zajednice/međusobna podrška" },
  { value: "02", label: "Hitni odgovor" },
  {value: "03", label: "Održavanje mira u zajednici" },
  { value: "04", label: "Socijalna pomoć" },
  { value: "05", label: "Osobna pomoć" },
  { value: "06", label: "Djeca i mladi" },
  { value: "07", label: "Ljudska prava, zagovaranje i politika" },
  { value: "08", label: "Ekonomska pravda" },
  { value: "09", label: "Na temelju vjere" },
  { value: "10", label: "vjersko volontiranje" },
  { value: "11", label: "Education" },
  { value: "12", label: "Zdravstvena njega" },
  { value: "13", label: "Okruženje" },
  { value: "14", label: "Prikupljanje podataka" },
  { value: "15", label: "Promicanje znanja" },
  { value: "16", label: "Promicanje trgovine" },
  { value: "17", label: "Pravo i pravne usluge" },
  { value: "18", label: "Culture" },
  { value: "19", label: "Recreation" },
  { value: "20", label: "Ostalo" },
]

export const programmeTypeList_sq = [
  { value: "01", label: "Aktiviteti i komunitetit/mbështetje reciproke" },
  { value: "02", label: "Përgjigjja e urgjencës" },
  { value: "03", label: "Paqeruajtja e komunitetit" },
  { value: "04", label: "Asistencë sociale" },
  { value: "05", label: "Asistencë personale" },
  { value: "06", label: "Fëmijët dhe të rinjtë" },
  { value: "07", label: "Të drejtat e njeriut, avokatia dhe politika" },
  { value: "08", label: "Drejtësia ekonomike" },
  { value: "09", label: "Bazuar në besim" },
  { value: "10", label: "vullnetarizmi fetar" },
  { value: "11", label: "Edukimi" },
  { value: "12", label: "Kujdes shëndetësor" },
  { value: "13", label: "Mjedis" },
  { value: "14", label: "Mbledhja e të dhënave" },
  { value: "15", label: "Promovimi i njohurive" },
  { value: "16", label: "Promovimi i tregtisë" },
  { value: "17", label: "Ligji dhe shërbimet ligjore" },
  { value: "18", label: "Kultura" },
  { value: "19", label: "Rekreacion" },
  { value: "20", label: "Tjetër" },
]

export const mainFundingOrganismList = [
  { value: "01", label: "private tender" },
  { value: "02", label: "public tender" },
  { value: "03", label: "private grant" },
  { value: "04", label: "public grant" },
  { value: "05", label: "donors" },
  { value: "06", label: "tuition fee" },
  { value: "07", label: "membership fee" },
  { value: "08", label: "organisation’s income" },
  { value: "09", label: "other" },
]

export const mainFundingOrganismList_es = [
  { value: "01", label: "licitación privada" },
  { value: "02", label: "licitación pública" },
  { value: "03", label: "subvención privada" },
  { value: "04", label: "subvención pública" },
  { value: "05", label: "donantes" },
  { value: "06", label: "tarifa de matrícula" },
  { value: "07", label: "cuota de membresía" },
  { value: "08", label: "ingresos de la organización" },
  { value: "09", label: "otro" },
]

export const mainFundingOrganismList_fr = [
  { value: "01", label : "appel d'offres privé" },
  { value: "02", label: "appel d'offres public" },
  { value: "03", label : "subvention privée" },
  { value: "04", label : "subvention publique" },
  { value: "05", label: "donateurs" },
  { value: "06", label : "frais de scolarité" },
  { value: "07", label : "frais d'adhésion" },
  { value: "08", label : "revenu de l'organisation" },
  { value: "09", label: "autre" },
]

export const mainFundingOrganismList_hr = [
  { value: "01", label: "privatni natječaj" },
  { value: "02", label: "javni natječaj" },
  { value: "03", label: "private grant" },
  { value: "04", label: "public grant" },
  { value: "05", label: "donors" },
  { value: "06", label: "školarina" },
  { value: "07", label: "članarina" },
  { value: "08", label: "prihod organizacije" },
  { value: "09", label: "ostalo" },
]

export const mainFundingOrganismList_sq = [
  { value: "01", label: "tender privat" },
  { value: "02", label: "tender publik" },
  { value: "03", label: "grant privat" },
  { value: "04", label: "grant publik" },
  { value: "05", label: "dhurues" },
  { value: "06", label: "pagesa e shkollimit" },
  { value: "07", label: "tarifa e anëtarësimit" },
  { value: "08", label: "të ardhurat e organizatës" },
  { value: "09", label: "tjetër" },
]

export const programmeSectorList = [
  { value: "01", label: "health and wellbeing" },
  { value: "02", label: "non-formal education and training" },
  { value: "03", label: "social" },
  { value: "04", label: "economy" },
  { value: "05", label: "social inclusion" },
  { value: "06", label: "environmental action" },
  { value: "07", label: "political action" },
  { value: "08", label: "sport and nature" },
  { value: "09", label: "volunteering" },
  { value: "10", label: "migration asylum and refugees" },
  { value: "11", label: "disability" },
  { value: "12", label: "older people" },
  { value: "13", label: "labour inclusion" },
  { value: "14", label: "youth" },
  { value: "15", label: "women and gendered violence" },
  { value: "16", label: "human rights" },
  { value: "17", label: "emergency response and humanitarian aid" },
  { value: "18", label: "cooperation and development" },
  { value: "19", label: "consumer protection" },
  { value: "20", label: "digital divide reduction" },
  { value: "21", label: "human technologies" },
  { value: "22", label: "animals protection" },
  { value: "23", label: "sustainable change and growth" },
  { value: "24", label: "other" },
]

export const programmeSectorList_es = [
  { value: "01", label: "health and wellbeing" },
  { value: "02", label: "non-formal education and training" },
  { value: "03", label: "social" },
  { value: "04", label: "economy" },
  { value: "05", label: "social inclusion" },
  { value: "06", label: "environmental action" },
  { value: "07", label: "political action" },
  { value: "08", label: "sport and nature" },
  { value: "09", label: "volunteering" },
  { value: "10", label: "migration asylum and refugees" },
  { value: "11", label: "disability" },
  { value: "12", label: "older people" },
  { value: "13", label: "labour inclusion" },
  { value: "14", label: "youth" },
  { value: "15", label: "women and gendered violence" },
  { value: "16", label: "human rights" },
  { value: "17", label: "emergency response and humanitarian aid" },
  { value: "18", label: "cooperation and development" },
  { value: "19", label: "consumer protection" },
  { value: "20", label: "digital divide reduction" },
  { value: "21", label: "human technologies" },
  { value: "22", label: "animals protection" },
  { value: "23", label: "sustainable change and growth" },
  { value: "24", label: "other" },
]

export const programmeSectorList_fr = [
  { value: "01", label : "santé et bien-être" },
  { value : "02", label : "éducation et formation non formelles" },
  { value: "03", label: "social" },
  { value: "04", label: "économie" },
  { value: "05", label: "inclusion sociale" },
  { value: "06", label : "action environnementale" },
  { value: "07", label : "action politique" },
  { value : "08", label : "sport et nature" },
  { value: "09", label: "bénévolat" },
  { value: "10", label : "migration, asile et réfugiés" },
  { value: "11", label: "handicap" },
  { value: "12", label : "personnes âgées" },
  { value: "13", label: "inclusion du travail" },
  { value: "14", label: "jeunesse" },
  { value: "15", label : "les femmes et les violences de genre" },
  { value: "16", label : "droits de l'homme" },
  { value: "17", label : "intervention d'urgence et aide humanitaire" },
  { value : "18", label : "coopération et développement" },
  { value: "19", label: "protection du consommateur" },
  { value: "20", label: "réduction de la fracture numérique" },
  { value: "21", label : "technologies humaines" },
  { value : "22", label : "protection des animaux" },
  { value: "23", label : "changement et croissance durables" },
  { value: "24", label: "autre" },
]

export const programmeSectorList_hr = [
  { value: "01", label: "zdravlje i blagostanje" },
   { value: "02", label: "neformalno obrazovanje i osposobljavanje" },
   { value: "03", label: "social" },
   { value: "04", label: "economy" },
   { value: "05", label: "socijalna uključenost" },
   { value: "06", label: "ekološka akcija" },
   { value: "07", label: "political action" },
   { value: "08", label: "sport i priroda" },
   { value: "09", label: "volontiranje" },
   { value: "10", label: "migration asylum and refugees" },
   { value: "11", label: "disability" },
   { value: "12", label: "stariji ljudi" },
   { value: "13", label: "labour inclusion" },
   { value: "14", label: "youth" },
   { value: "15", label: "žene i rodno uvjetovano nasilje" },
   { value: "16", label: "ljudska prava" },
   { value: "17", label: "hitni odgovor i humanitarna pomoć" },
   { value: "18", label: "suradnja i razvoj" },
   { value: "19", label: "zaštita potrošača" },
   { value: "20", label: "smanjenje digitalne podjele" },
   { value: "21", label: "human technology" },
   { value: "22", label: "zaštita životinja" },
   { value: "23", label: "održiva promjena i rast" },
   { value: "24", label: "ostalo" },
]

export const programmeSectorList_sq = [
  { value: "01", label: "shëndet dhe mirëqenie" },
  { value: "02", label: "arsim dhe trajnim joformal" },
  { value: "03", label: "sociale" },
  { value: "04", label: "ekonomi" },
  { value: "05", label: "përfshirje sociale" },
  { value: "06", label: "veprim mjedisor" },
  { value: "07", label: "veprim politik" },
  { value: "08", label: "sporti dhe natyra" },
  { value: "09", label: "vullnetarizëm" },
  { value: "10", label: "azili i migracionit dhe refugjatët" },
  { value: "11", label: "paaftësi" },
  { value: "12", label: "të moshuarit" },
  { value: "13", label: "përfshirja e punës" },
  { value: "14", label: "të rinjtë" },
  { value: "15", label: "gratë dhe dhuna gjinore" },
  { value: "16", label: "të drejtat e njeriut" },
  { value: "17", label: "përgjigje emergjente dhe ndihmë humanitare" },
  { value: "18", label: "bashkëpunim dhe zhvillim" },
  { value: "19", label: "mbrojtja e konsumatorit" },
  { value: "20", label: "Reduktimi i ndarjes dixhitale" },
  { value: "21", label: "teknologji njerëzore" },
  { value: "22", label: "mbrojtja e kafshëve" },
  { value: "23", label: "ndryshim dhe rritje e qëndrueshme" },
  { value: "24", label: "tjetër" },
]